# Generated by Django 5.2.8 on 2025-12-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctor_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_online",
        ),
        migrations.AddField(
            model_name="chatlog",
            name="facial_emotion_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="multimodal_prediction",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="FacialEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="facial_images/"
                    ),
                ),
                ("emotions", models.JSONField(default=dict)),
                (
                    "primary_emotion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facial_emotion",
                        to="accounts.chatlog",
                    ),
                ),
            ],
        ),
    ]
