# Generated by Django 5.2.8 on 2025-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_doctor_is_online_chatlog_facial_emotion_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mentalhealthquiz",
            name="facial_emotion_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
