# Generated by Django 5.2.8 on 2026-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_mentalhealthquiz_facial_emotion_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="concentration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("terrible", "Terrible"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="energy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("moderate", "Moderate"),
                    ("low", "Low"),
                    ("very_low", "Very Low"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="physical_health",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("terrible", "Terrible"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="sleep_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("terrible", "Terrible"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="social_interaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_satisfied", "Very Satisfied"),
                    ("satisfied", "Satisfied"),
                    ("neutral", "Neutral"),
                    ("dissatisfied", "Dissatisfied"),
                    ("very_dissatisfied", "Very Dissatisfied"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="stress_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("extreme", "Extreme"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
